### ISSUE TITLE
Vehicle Path Nodes Unselectable

### ISSUE THREAD

**Issue by Hard-Copy** [TwoTwoEleven/MicroManage#28] opened 2022-10-29 04:43 UTC
Unable to target or edit vehicle nodes.  This is the only Mod I use.

**Comment by daviian** [comment] 2022-10-31 13:50
Duplicate of #22

**Comment by TwoTwoEleven** [comment] 2022-11-01 06:39
This has been fixed internally and will be available again in the upcoming 1.0.5 release.

**Closed as completed by TwoTwoEleven** 2022-11-01 06:39 UTC
